name: SSHX Direct Runner VPS

on:
  workflow_dispatch: # Yeh Actions tab se manual run karne ke liye hai

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 999999999999999999999999

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget nano htop

      - name: Connect and Launch SSHX
        run: |
          echo "📥 Installing sshx on GitHub runner..."
          curl -sSf https://sshx.io/get | sh
          
          echo "🚀 Starting sshx session..."
          echo "Logs check karo, wahan https://sshx.io/s/... wala link milega."
          
          # Run sshx. Yeh command terminal block karke rakhegi taaki runner chalta rahe.
          sshx
