name: Tmate Direct Runner VPS

on:
  workflow_dispatch: # Actions tab se manual run karne ke liye

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 ghante ki hard limit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget nano htop

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          # Isko true karne par sirf aapki GitHub account SSH key se hi login hoga
          # False rakha hai taaki directly web link ya public ssh se connect ho sako
          limit-access-to-actor: false
